services:
  server:
    image: golang:latest
    container_name: fiber-auth
    working_dir: /app
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: go run main.go
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mariadb:latest
    container_name: fiber-auth-db
    working_dir: /db
    env_file: .env
    volumes:
      - "./data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 3
      