services:
  server:
    image: golang:latest
    container_name: fiber-auth
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: .env
    command: go run main.go
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    container_name: fiber-auth-db
    ports:
      - "5432:5432"
    env_file: .env
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 5
